steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/abiding-result-412222/nyande-100942795/nodejs-app:${COMMIT_SHA}', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/abiding-result-412222/nyande-100942795/nodejs-app:${COMMIT_SHA}']

options:
  defaultLogsBucket: 'REGIONAL_USER_OWNED_BUCKET'

images:
   - 'us-central1-docker.pkg.dev/abiding-result-412222/nyande-100942795/nodejs-app:${COMMIT_SHA}'
